# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created: Sun Sep  8 14:30:08 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName(_fromUtf8("Form1"))
        Form1.setWindowModality(QtCore.Qt.ApplicationModal)
        Form1.setEnabled(True)
        Form1.resize(647, 436)
        Form1.setMinimumSize(QtCore.QSize(647, 436))
        Form1.setMaximumSize(QtCore.QSize(647, 436))
        Form1.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form1.setWindowIcon(icon)
        self.groupBox = QtGui.QGroupBox(Form1)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 271, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(70, 40, 191, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 64, 151, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(218, 10, 44, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 70, 75, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/salir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(14, 64, 14, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(14, 40, 41, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(237, 37, 21, 21))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8("icons/usuario.png")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.groupBox_2 = QtGui.QGroupBox(Form1)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 10, 351, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(6, 20, 341, 141))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_crear = QtGui.QWidget()
        self.tab_crear.setObjectName(_fromUtf8("tab_crear"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_crear)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 90, 75, 23))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/crea.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.label_7 = QtGui.QLabel(self.tab_crear)
        self.label_7.setGeometry(QtCore.QRect(94, 50, 65, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_crear)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 16, 41, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_crear)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 46, 41, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_5 = QtGui.QLabel(self.tab_crear)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 65, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.tab_crear)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 65, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_6 = QtGui.QLabel(self.tab_crear)
        self.label_6.setGeometry(QtCore.QRect(94, 20, 65, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(self.tab_crear)
        self.label_9.setGeometry(QtCore.QRect(210, 20, 72, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_crear)
        self.label_10.setGeometry(QtCore.QRect(210, 50, 72, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/crear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_crear, icon3, _fromUtf8(""))
        self.tab_verificar = QtGui.QWidget()
        self.tab_verificar.setObjectName(_fromUtf8("tab_verificar"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_verificar)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 20, 124, 23))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/buscar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton = QtGui.QPushButton(self.tab_verificar)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 91, 23))
        self.pushButton.setIcon(icon4)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_9 = QtGui.QPushButton(self.tab_verificar)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 50, 124, 23))
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/verificar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_verificar, icon5, _fromUtf8(""))
        self.tab_reservar = QtGui.QWidget()
        self.tab_reservar.setObjectName(_fromUtf8("tab_reservar"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_reservar)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 76, 91, 23))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/palomita.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_reservar)
        self.lineEdit_11.setGeometry(QtCore.QRect(159, 14, 41, 20))
        self.lineEdit_11.setText(_fromUtf8(""))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_21 = QtGui.QLabel(self.tab_reservar)
        self.label_21.setGeometry(QtCore.QRect(9, 48, 70, 13))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_reservar)
        self.label_22.setGeometry(QtCore.QRect(10, 80, 70, 13))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_19 = QtGui.QLabel(self.tab_reservar)
        self.label_19.setGeometry(QtCore.QRect(9, 18, 70, 13))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_reservar)
        self.lineEdit_13.setGeometry(QtCore.QRect(89, 78, 111, 20))
        self.lineEdit_13.setText(_fromUtf8(""))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_20 = QtGui.QLabel(self.tab_reservar)
        self.label_20.setGeometry(QtCore.QRect(89, 18, 66, 13))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_reservar)
        self.lineEdit_12.setGeometry(QtCore.QRect(88, 46, 111, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.label_11 = QtGui.QLabel(self.tab_reservar)
        self.label_11.setGeometry(QtCore.QRect(211, 17, 72, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("icons/reservar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_reservar, icon7, _fromUtf8(""))
        self.tab_eliminar = QtGui.QWidget()
        self.tab_eliminar.setObjectName(_fromUtf8("tab_eliminar"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_eliminar)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 3, 311, 51))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 20, 75, 23))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("icons/cruz.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon8)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(116, 20, 111, 20))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_eliminar)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 60, 311, 51))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(82, 20, 41, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(13, 24, 71, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 20, 75, 24))
        self.pushButton_5.setIcon(icon8)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(207, 20, 101, 24))
        self.pushButton_3.setIcon(icon8)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("icons/eliminar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_eliminar, icon9, _fromUtf8(""))
        self.groupBox_9 = QtGui.QGroupBox(Form1)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 271, 61))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_23 = QtGui.QLabel(self.groupBox_9)
        self.label_23.setGeometry(QtCore.QRect(10, 34, 57, 13))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 30, 151, 20))
        self.lineEdit_14.setFrame(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_13 = QtGui.QLabel(self.groupBox_9)
        self.label_13.setGeometry(QtCore.QRect(240, 30, 21, 21))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setPixmap(QtGui.QPixmap(_fromUtf8("icons/mundo.png")))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.textEdit = QtGui.QTextEdit(Form1)
        self.textEdit.setGeometry(QtCore.QRect(10, 190, 631, 241))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))

        self.retranslateUi(Form1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), Form1.close)
        QtCore.QMetaObject.connectSlotsByName(Form1)
        Form1.setTabOrder(self.lineEdit_14, self.lineEdit_2)
        Form1.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Form1.setTabOrder(self.lineEdit_3, self.pushButton_7)
        Form1.setTabOrder(self.pushButton_7, self.pushButton)
        Form1.setTabOrder(self.pushButton, self.pushButton_2)
        Form1.setTabOrder(self.pushButton_2, self.pushButton_9)
        Form1.setTabOrder(self.pushButton_9, self.lineEdit_11)
        Form1.setTabOrder(self.lineEdit_11, self.lineEdit_12)
        Form1.setTabOrder(self.lineEdit_12, self.lineEdit_13)
        Form1.setTabOrder(self.lineEdit_13, self.pushButton_6)
        Form1.setTabOrder(self.pushButton_6, self.lineEdit_10)
        Form1.setTabOrder(self.lineEdit_10, self.lineEdit_15)
        Form1.setTabOrder(self.lineEdit_15, self.pushButton_4)
        Form1.setTabOrder(self.pushButton_4, self.lineEdit_9)
        Form1.setTabOrder(self.lineEdit_9, self.pushButton_5)
        Form1.setTabOrder(self.pushButton_5, self.pushButton_3)
        Form1.setTabOrder(self.pushButton_3, self.pushButton_8)
        Form1.setTabOrder(self.pushButton_8, self.textEdit)
        Form1.setTabOrder(self.textEdit, self.tabWidget)

    def retranslateUi(self, Form1):
        Form1.setWindowTitle(_translate("Form1", "DHCP Remoto", None))
        self.groupBox.setTitle(_translate("Form1", "Informacion de Usuario :", None))
        self.label.setText(_translate("Form1", "Nombre de Usuario", None))
        self.label_2.setText(_translate("Form1", "Ip:", None))
        self.label_3.setText(_translate("Form1", "2013/9/1", None))
        self.pushButton_8.setToolTip(_translate("Form1", "Salir de DHCP Remoto", None))
        self.pushButton_8.setText(_translate("Form1", "Salir", None))
        self.label_4.setText(_translate("Form1", "Ip:", None))
        self.label_14.setText(_translate("Form1", "Nombre:", None))
        self.groupBox_2.setTitle(_translate("Form1", "Configuración de Scope Remoto - DHCP ", None))
        self.tabWidget.setToolTip(_translate("Form1", "<html><head/><body><p>Configuracion de Scope DHCP</p></body></html>", None))
        self.pushButton_7.setToolTip(_translate("Form1", "Crear Configuracion DHCP", None))
        self.pushButton_7.setText(_translate("Form1", "Crear", None))
        self.label_7.setText(_translate("Form1", "255.255.255.", None))
        self.lineEdit_2.setToolTip(_translate("Form1", "Ultimo Octeto IP", None))
        self.lineEdit_2.setInputMask(_translate("Form1", "000;#", None))
        self.lineEdit_2.setText(_translate("Form1", "0", None))
        self.lineEdit_3.setToolTip(_translate("Form1", "Ultimo Octeto IP", None))
        self.lineEdit_3.setInputMask(_translate("Form1", "000;#", None))
        self.lineEdit_3.setText(_translate("Form1", "0", None))
        self.label_5.setText(_translate("Form1", "Rango Inicial:", None))
        self.label_8.setText(_translate("Form1", "Rango Final:", None))
        self.label_6.setText(_translate("Form1", "255.255.255.", None))
        self.label_9.setText(_translate("Form1", "Rango Invalido", None))
        self.label_10.setText(_translate("Form1", "Rango Invalido", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_crear), _translate("Form1", "Crear", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_crear), _translate("Form1", "Crear Scope", None))
        self.pushButton_2.setToolTip(_translate("Form1", "Verificar IP Reservadas", None))
        self.pushButton_2.setText(_translate("Form1", " IP Reservadas", None))
        self.pushButton.setToolTip(_translate("Form1", "Verificar Configuracion DHCP", None))
        self.pushButton.setText(_translate("Form1", "Scope", None))
        self.pushButton_9.setToolTip(_translate("Form1", "Verificar IP Reservadas", None))
        self.pushButton_9.setText(_translate("Form1", "Clientes Conectados", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_verificar), _translate("Form1", "Verificar", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_verificar), _translate("Form1", "Verificar Existencias DHCP", None))
        self.pushButton_6.setToolTip(_translate("Form1", "Reservar IP", None))
        self.pushButton_6.setText(_translate("Form1", "Reservar", None))
        self.lineEdit_11.setToolTip(_translate("Form1", "Ultimo Octeto de IP", None))
        self.lineEdit_11.setInputMask(_translate("Form1", "000;#", None))
        self.label_21.setText(_translate("Form1", "MacAddress:", None))
        self.label_22.setText(_translate("Form1", "Nombre: ", None))
        self.label_19.setText(_translate("Form1", "Ip a Reservar:", None))
        self.lineEdit_13.setToolTip(_translate("Form1", "Nombre a Reservar", None))
        self.label_20.setText(_translate("Form1", "255.255.255.", None))
        self.lineEdit_12.setToolTip(_translate("Form1", "Direccion Unica MacAddress", None))
        self.lineEdit_12.setInputMask(_translate("Form1", "HH:HH:HH:HH:HH:HH;_", None))
        self.lineEdit_12.setText(_translate("Form1", ":::::", None))
        self.label_11.setText(_translate("Form1", "Rango Invalido", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reservar), _translate("Form1", "Reservar IP", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_reservar), _translate("Form1", "Reservar Direccion  IP", None))
        self.groupBox_3.setTitle(_translate("Form1", "Eliminar IP Reservada", None))
        self.lineEdit_10.setToolTip(_translate("Form1", "IP a Reservar", None))
        self.lineEdit_10.setInputMask(_translate("Form1", "000.000.000.000;_", None))
        self.lineEdit_10.setText(_translate("Form1", "...", None))
        self.pushButton_4.setToolTip(_translate("Form1", "Eliminar IP Reservada", None))
        self.pushButton_4.setText(_translate("Form1", "Eliminar", None))
        self.lineEdit_15.setToolTip(_translate("Form1", "Direccion Unica MacAddress", None))
        self.lineEdit_15.setInputMask(_translate("Form1", "HH:HH:HH:HH:HH:HH;_", None))
        self.lineEdit_15.setText(_translate("Form1", ":::::", None))
        self.groupBox_4.setTitle(_translate("Form1", "Eliminar IP", None))
        self.lineEdit_9.setToolTip(_translate("Form1", "Ultimo Octeto de IP", None))
        self.lineEdit_9.setInputMask(_translate("Form1", "000;#", None))
        self.label_17.setText(_translate("Form1", "255.255.255.", None))
        self.pushButton_5.setToolTip(_translate("Form1", "Eliminar IP", None))
        self.pushButton_5.setText(_translate("Form1", "Eliminar", None))
        self.pushButton_3.setToolTip(_translate("Form1", "Eliminar Configuracion DHCP", None))
        self.pushButton_3.setText(_translate("Form1", "Eliminar Scope", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_eliminar), _translate("Form1", "Eliminar", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_eliminar), _translate("Form1", "Eliminar DHCP y Objetos", None))
        self.groupBox_9.setTitle(_translate("Form1", "Datos del Servidor DHCP:", None))
        self.label_23.setText(_translate("Form1", "Ip Servidor:", None))
        self.lineEdit_14.setToolTip(_translate("Form1", "<html><head/><body><p>Ip Servidor POS</p></body></html>", None))
        self.lineEdit_14.setInputMask(_translate("Form1", "000.000.000.000;_", None))
        self.textEdit.setToolTip(_translate("Form1", "Consola de Salida", None))
        self.textEdit.setHtml(_translate("Form1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Consola de Salida</span></p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form1 = QtGui.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form1)
    Form1.show()
    sys.exit(app.exec_())

